### ISSUE TITLE
Feature: Issue Templates

### ISSUE THREAD

**Issue by moorej-oci** [objectcomputing/check-ins#1548]
It would be helpful to implement github issue templates to guide submission of bug reports and feature requests. This would give a common structure to requests and prompt for information people might not think to add (browser version, screenshots, etc.)

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by pieperm** [comment]
Resolved by https://github.com/objectcomputing/check-ins/commit/e36dc8999185be22aa66e366cb363e728edfa9de
