### ISSUE TITLE
Bug: Feedback is out of order

### ISSUE THREAD

**Issue by moorej-oci** [objectcomputing/check-ins#1552]
As seen in the picture feedback for my PDF starts at 2 and goes to 4. Not pictured is then 1 and 3 for a final order of 2,4,1,3. Not a breaking issue but the answers confused me until I realized this
![image](https://user-images.githubusercontent.com/52177452/135670500-f9970852-f33b-4509-b8d3-229c85633add.png)

**Comment by pieperm** [comment]
I believe I have found a fix for this, though I'm having trouble verifying that it works. The steps taken in #1424 result in a `403: You are not allowed to do this operation`
