### ISSUE TITLE
Bug: User is unauthorized to do this operation

### ISSUE THREAD

**Issue by mitza-oci** [objectcomputing/check-ins#1558]
This message was seen when reviewing a previous Check-In for a Development Partner

**Comment by mitza-oci** [comment]
I don't think I have anyone who had a different PDL earlier this year.

**Comment by pieperm** [comment]
After some further investigation into this bug, it seems the problem stems from attempting to update notes from a previous check-in. When navigating to a previous check-in, the system attempts to make a PUT request to the private notes service (`PUT http://localhost:8080/services/private-notes`) as well as the notes service (`PUT http://localhost:8080/services/checkin-notes`)

This seems to occur regardless of whether the current PDL is the same as the one during the check-in. Going to see if I can find a fix.
