### ISSUE TITLE
Must touch start date to save user

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#1614]
**Describe the bug**
Even though the start date is auto populated, you cannot save a user without first adjusting the value of that field

**To Reproduce**
1. Go to Admin
2. Click on Users
3. Click Add User
4. Fill out everything other than the start date
5. Hit save
6. Nothing happens...

**Expected behavior**
The user is saved.

**Comment by smithj11** [comment]
Bugfix branch merged
