### ISSUE TITLE
Add backend support for different kinds of feedback questions [S?]

### ISSUE THREAD

**Issue by smithj11** [objectcomputing/check-ins#1645]
**Is your feature request related to a problem? Please describe.**
Currently, only text questions are supported for feedback. However, templates often demand slider or multiple-choice options. These are currently not supported.

**Describe the solution you'd like**
Alter the backend on questions/answers to support different question/answer formats, such as selection,  multi-selection, slider/scale, dropdown.

**Additional context**

**Comment by pieperm** [comment]
This issue has been resolved by issue #1646
