### ISSUE TITLE
Is there a way to automatically add a user to KnowBe4? API? Some call that results in the creation of a user.

### ISSUE THREAD

**Issue by sharmag04** [objectcomputing/check-ins#1736]
- [x] Determine if you can create a user on KnowB4.

- [x] Give an example of an API schema for the creation of a user on KnowB4.

**Comment by 1mbalducci** [comment]
KnowBe4 Notes: @mkimberlin 

https://us.api.knowbe4.com/v1/users/{user_id}

-API available to Platinum and Diamond customers only
-KnowBe4’s APIs are [REST APIs](http://en.wikipedia.org/wiki/Representational_State_Transfer) that allow you to pull phishing, training, user, and group data from the KnowBe4 console. Data is returned in a JSON structure by default--no additional parameter is needed.
-APIs use resource-oriented URLs for requests and HTTP response codes for error handling. HTTP features, such as HTTP authentication and HTTP verbs, are built-in and understood by standard HTTP clients.
-must use the Base URL of https://us.api.knowbe4.com/

Authentication
-Authenticate your account by including your secret API key in the request, needs to be private (get this from account settings)
		Authorization: Bearer <your_token>
-All API requests must be made over HTTPS. Calls made over plain HTTP will fail. API requests without authentication will also fail.
-Please note that Reporting APIs and User Event APIs do not share an API key. User Event API keys must be generated in the [User Event API Management Console](https://training.knowbe4.com/event_api_admin#/).

Response Format
The supported response format is JSON. The response will be returned in a JSON structure by default--no additional parameter is needed.


{
  "id": 667542,
  "employee_number": "19425",
  "first_name": "William",
  "last_name": "Marcoux",
  "job_title": "VP of Sales",
  "email": "wmarcoux@kb4-demo.com",
  "phish_prone_percentage": 14.235,
  "phone_number": "555-554-2222",
  "extension": "42",
  "mobile_phone_number": "555-553-4422",
  "location": "Office A",
  "division": "Sales",
  "manager_name": "Michael Scott",
  "manager_email": "mscott@kb4-demo.com",
  "adi_manageable": false,
  "adi_guid": null,
  "groups": [
    3264
  ],
  "current_risk_score": 45.742,
  "risk_score_history": [
    {
      "risk_score": 45.742,
      "date": "2019-03-12"
    }
  ],
  "aliases": [
    "alias_email@kb4-demo.com"
  ],
  "joined_on": "2019-04-02T15:02:38.000Z",
  "last_sign_in": "2019-04-02T15:02:38.000Z",
  "status": "active",
  "organization": "KB4-Demo",
  "department": "Sales",
  "language": "English - United States",
  "comment": "Low PPP",
  "employee_start_date": "2019-04-02T15:02:38.000Z",
  "archived_at": null,
  "custom_field_1": "Building C, 4th Floor",
  "custom_field_2": null,
  "custom_field_3": null,
  "custom_field_4": null,
  "custom_date_1": "1986-11-26",
  "custom_date_2": null
}




Questions/Concerns:
1.Do we have an anonymized account?
	-Anonymized KnowBe4 accounts (accounts that have elected to make their user data anonymous) will not be able to retrieve 	any anonymized data. See our [Anonymous Console](https://support.knowbe4.com/hc/en-us/articles/115009509107) documentation to review what data will be available on anonymized 		accounts.

2.API keys need to be kept private.  How will we do this while merging to our public git project?
3.I see we can get a list of all users, list of users in a group, and a specific user, but I do not see that there is an api way to CREATE a user.
4. To access and use it do you just use the baseurl? https://us.api.knowbe4.com
