### ISSUE TITLE
 Design the HR page (L)

### ISSUE THREAD

**Issue by sharmag04** [objectcomputing/check-ins#1737]
- [x] indicate what type of hire (W-2 or contract/1099)
- [x] enter name
- [x] enter email address
- [x] upload accepted offer letter (goes to google drive)
- [x] upload employment agreement (goes to sign request)
- [x] upon submit, email is sent to the new employee
- [x] Is there currently an HR process within checkins? ANSWER: no.
- [x] determine where HR accesses to add a user
- [x] determine where HR sees notif. about user 
- [x] determine how HR can close out a user once onboarding is complete

Required: benefits should not show up in the user's flow if contract is selected.

https://www.figma.com/file/xTkvFcaXvpzqmYN3KMqPjX/Intern-Design-Sprint-2022-V2?node-id=500%3A955

**Comment by S78901** [comment]
This ticket has been completed & reviewed. The accompanying Figma is accurate to a high degree of specificity. Where deviations may occur, they will be noted in individual ticket's success criteria.
