### ISSUE TITLE
As an HR user, clicking on the "Delete" button will delete the user from the database

### ISSUE THREAD

**Issue by MatthewBackes** [objectcomputing/check-ins#1942]
- [ ] Remove the onboardee from the “Onboardees” table
- [ ] Remove the onboardee’s notifications from the “Notification” box
- [ ] Once I'm back to the "Progress" main page, I can view the updated “Onboardees” table and “Notification” box which no longer contain info about the onboardee I just finished onboarding

**Comment by thelenw** [comment]
This functionality exists in context of the current Check-Ins infrastructure, so the issue is resolved.
