### ISSUE TITLE
As an HR user, clicking on the "Finish Onboarding" button will delete the user and archive appropriate documents.

### ISSUE THREAD

**Issue by MatthewBackes** [objectcomputing/check-ins#1943]
- [ ] Remove the onboardee from the “Onboardees” table
- [ ] Remove the onboardee’s notifications from the “Notification” box
- [ ] Once I'm back to the "Progress" main page, I can view the updated “Onboardees” table and “Notification” box which no longer contain info about the onboardee I just finished onboarding
-  [ ] Create the object computing check-ins user and email
- [ ] Archive documents and associate them with new user

**Comment by thelenw** [comment]
This is covered via ```Admin > Permissions``` + ```Admin > Users > Add Member``` + ```Admin > Users > Edit Member > Delete```.

If HR-specific functionality is desired, mention it in a new issue about deshelved Onboarding.
