### ISSUE TITLE
BE: As an HR user I’m able to click on the “Reset Onboardee” button on the “Edit Onboardee” pop-up window

### ISSUE THREAD

**Issue by MisheelSodgerel** [objectcomputing/check-ins#1947]
Clicking on the "Reset Onboardee" button will:
- [ ] Update the onboardee’s information in the “Onboardees” table, the “Onboardee Details” page, and the “Documents & Surveys” table
- [ ] Open a “Onboardee Reset” pop-up window message that can be OK’d closed
- [ ] Update the onboardee’s information in the “Onboardees” table and the “Notification” box on the “Progress” main page (set progress = “Not accessed” and their past notifications removed)
- [ ] create profile class
- [ ] implementation services
- [ ] DTOs
- [ ] controller
- [ ] implementation testing

- [ ] use appropriate state/store mechanism

**Comment by thelenw** [comment]
This is covered via ```impersonating HR``` (Revolver Ocelot) and inspecting all accessible ```Directory``` and other pages, which do not yield undue access to view or manage employee information.

If this is requesting the functionality listed, what is the point? The mentioned facets no longer exist. How is onboarding usually performed? To deshelve onboarding functionality or address anything mentioned here, create a new issue according to the existing Check-Ins system.
