### ISSUE TITLE
Profile images should not be open to unauthenticated users

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#1956]
**Describe the bug**
User profile images are open to unauthed users...see: [https://checkins.objectcomputing.com/services/member-profiles/member-photos/lynchb@objectcomputing.com](https://checkins.objectcomputing.com/services/member-profiles/member-photos/lynchb@objectcomputing.com)

**To Reproduce**
Click the link above, and it works no matter what.

**Expected behavior**
Forced to login if not already logged in

**Comment by borinquenkid** [comment]
It seems the controller is properly annotated 

`@Controller("/services/member-profiles/member-photos")`
`@Secured(SecurityRule.IS_AUTHENTICATED)`
`@Produces(MediaType.IMAGE_PNG)`
`@Tag(name = "member photo")`
`public class MemberPhotoController {`

**Comment by borinquenkid** [comment]
Also I can only view the image if I am authenticated to Object Computing GSuite

**Comment by vhscom** [comment]
> Also I can only view the image if I am authenticated to Object Computing GSuite

Indeed a Google login is now required to access member profiles, and is restricted to Organization members only.

<img width="1058" alt="Screenshot 2024-04-23 at 1 35 18 PM" src="https://github.com/objectcomputing/check-ins/assets/97140109/ac0a3a0f-ef76-499c-815c-33d88e68aa6f">

Closing this issue as stale.
