### ISSUE TITLE
Attempting to send an email results in TypeError

### ISSUE THREAD

**Issue by zsbrown97** [objectcomputing/check-ins#1978]
**Describe the bug**
When composing an email with no formatting, an "Uncaught TypeError" is thrown, stating "Cannot read properties of undefined (reading 'memberId')".

**To Reproduce**
1. As an admin, go to Admin -> Send Email
2. Select "Text"
3. Fill out the subject and email content like normal

**Expected behavior**
The page should advance to Select Recipients

**Desktop (please complete the following information):**
 - OS: macOS 13.0 (Ventura)
 - Browser: Chrome (ver. 107.0.5304.87), Firefox (ver. 106.0.5), Safari (ver. 16.1)

**Additional context**
The error points to `selectors.js:151:1`, in the `selectMappedUserRoles` selector.

I have yet to test with an MJML file. I shall update this issue accordingly if possible/necessary.

**Comment by mkimberlin** [comment]
No longer reproducible.
