### ISSUE TITLE
Send Reminder button does not seem to work

### ISSUE THREAD

**Issue by brianjohnson5972** [objectcomputing/check-ins#1981]
**Describe the bug**
I have pressed the "Send Reminder" button next to people who have not responded to requests to fill out feedback and they have not seen any new request.
I presume this is either a problem with the "Send Reminder" functionality, or else there is something about these specific accounts that is preventing them from getting any communication. The users are Kevin Heifner, Alice Daimes, Wayne Kaiser, Ciju John, Jack DiSalvatore, and Nate Minshew.

**To Reproduce**
1. Go to 'View Feedback'
2. Click on 'View All Responses'
3. Scroll down to an Overdue request
4. Click on Alarm clock icon
5. Check with person to see if any reminder was received

**Expected behavior**
That the user would get something to remind them to fill out the form

**Screenshots**
![image](https://user-images.githubusercontent.com/10270043/202227343-64822a83-fdd5-40cd-a5bf-4a2ff38eb8d0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 107.0.5304.107 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
None

**Comment by mkimberlin** [comment]
I've tried to reproduce this, but to no effect. Can you confirm whether it is still occurring for you?
