### ISSUE TITLE
Feature Request: Self-Reported Tech Skills Report

### ISSUE THREAD

**Issue by JasonTypesCodes** [objectcomputing/check-ins#2021]
I think it would be great to have a report from check-ins that shows a list of all self-reported skills and, for each skill, a count of the number of individuals that identified as each "level" of experience of that skill.  Something like:

| Skill | Interest Count | Novice Count | Intermediate Count | Advanced Count | Expert Count |
|--------|-----------------------|----------------------|------------------------------|--------------------------|--------------------|

It would be helpful to capture (and snapshot) this information monthly to get a picture of the self-reported skill strengths and weaknesses in the org and how they have progressed over time.

**Comment by thelenw** [comment]
This is covered between ```Admin > Skills``` and ```Reports > Skills``` so is presently resolved. Please reopen this if a different formatting of the self-reported skills needs to be implemented. Please specify that formatting for implementation.
