### ISSUE TITLE
Reordering of list of employees

### ISSUE THREAD

**Issue by AndrewBarbaglia** [objectcomputing/check-ins#2023]
**Describe the bug**
When typing a name under "select employees" and when deleting text in search bar, the list of employees reorders by first name instead of last. Happens on desktop and mobile

**To Reproduce**
1. Go to check-ins and search for an employee, under "Admin" then "User"
2. Type in a name
3. Delete or backspace the name
4. See error or employees reordered by first name

**Expected behavior**
Employees should be ordered by last name

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [Version 114.0.5735.133]

**Smartphone (please complete the following information):**
 - Device: [iPhone13]
 - OS: [e.g. iOS16.3.1]
 - Browser [e.g. safari]
 - Version [e.g. 13]

**Additional context**

**Comment by S78901** [comment]
Bug fix open:
https://github.com/objectcomputing/check-ins/pull/2158
