### ISSUE TITLE
Total batch Email size exceeds individual max Email size

### ISSUE THREAD

**Issue by malee1975** [objectcomputing/check-ins#2100]
**Describe the bug**
The total Email size for MailJet is !5 including attachments. If Emails are batched for example a batch of 4 emails each of a size of 4 MB the API throws a 413 error: "Request Entity Too Large". 

**To Reproduce**
1. Send a batch of Emails that exceed 15Mb in total size without a single email exceeding this threshold

**Expected behavior**
It is expected that within a batch that each Email is checked on an individual basis. There appear to be no documentation on batch size limits. 
.
**Desktop (please complete the following information):**
 - Windows
 - Node JS

**Comment by mkimberlin** [comment]
@malee1975 Thanks for opening this issue. We haven't pushed to encourage adoption of this platform at all yet. So, documentation has been low on the priority list up to this point. That said, completely fair criticism! I would love to understand how you are using the app that resulted in blowing out that size limit. I think taking into mind the size when batching should be feasible though.

**Comment by malee1975** [comment]
Wrong thread
