### ISSUE TITLE
Add a Category to Skills

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2106]
**Is your feature request related to a problem? Please describe.**
The skills list is unwieldy. They are hard to list, report on, or visualize.

**Describe the solution you'd like**
I'd like to add a category for each skill. Skill categories would likely be kept in their own table and skills could be uncategorized (not yet assigned a category). It may be worthwhile to allow categories to be hierarchical as well. i.e.:

 * Essential Skills
 * Management Skills
 * Tools 
 * Languages
 * Libraries & Frameworks
   * Java
   * JavaScript
   * C / C++
   * GoLang
   * Rust

**Describe alternatives you've considered**
Other UI changes, but breaking down skills into types and/or categories seems to be the most flexible option.

**Comment by pieperm** [comment]
**Update:** A skill can be part of zero, one, or more categories. There will be no hierarchy involved, so skills will be part of categories,  but there will be no subcategories.

**Comment by pieperm** [comment]
Definition of Done:
- [ ] Create skill categories
- [ ] Update skill category
- [ ] Add and remove skills to a category
- [ ] Delete a skill category
