### ISSUE TITLE
Show Reports menu item for anyone with a view report permission

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2109]
As a user with any "view report" permission, I want the Reports menu item to be visible, so that I can access reports relevant to my work.

Acceptance criteria:
- [x] The application checks the user's permissions for the ability to view any reports.
- [x] If the user has any permission that allows for viewing reports, the Reports menu item is displayed.
- [x] If no such permission is found, the Reports menu item is hidden.

**Comment by ZacharyKlein** [comment]
@mkimberlin Looking at `Permissions.java`, I see this list of "report" permissions: 

`    CAN_VIEW_SKILLS_REPORT,
    CAN_VIEW_RETENTION_REPORT,
    CAN_VIEW_ANNIVERSARY_REPORT,
    CAN_VIEW_BIRTHDAY_REPORT,
    CAN_VIEW_PROFILE_REPORT,`

Is it fair to say that any of those permissions would allow the "REPORT" menu item to be visible? Or should there be a generic "CAN_VIEW_REPORTS" permission that we look for?

**Comment by ZacharyKlein** [comment]
Hah, I just realized you answered my question in the description - "any "view report" permission". My bad!

**Comment by mkimberlin** [comment]
Closed by #2117
