### ISSUE TITLE
Convert Team Skills report to use a transfer list

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2111]
As a user, I want to use a transfer list component to filter and select team members for the "Team Skills" report, so that I can easily identify the skills of various groups within the company.

Acceptance criteria:
 - [ ] The "Team Skills" report page is updated to display a transfer list component instead of the existing team selection options.
The transfer list component allows filtering by the following options:
   - [ ] Team membership (through a multi-select dropdown)
   - [ ] Guild membership (through a multi-select dropdown)
   - [ ] Manager (through a multi-select dropdown)
   - [ ] Skills possessed (through a multi-select dropdown)
   - [ ] Title (through a multi-select dropdown)
   - [ ] Name
   - [ ] Location (through a multi-select dropdown)
 - [ ] Filtering by manager includes two options:
   - [ ] Show all employees reporting to the selected manager (including their direct reports and indirect reports)
   - [ ] Show only the selected manager's direct reports
 - [ ] When filtering by Manager, the user should have the option to only include direct reports
   - [ ] The option to only include direct reports should not be selected by default

**Comment by S78901** [comment]
@ZacharyKlein @mkimberlin Is this ticket open/still a priority?
