### ISSUE TITLE
Order team skill report by number of matched skills and skill level

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2113]
As a user, I want the "Team Skills" report to be ordered first by the number of matching skills, then by the average skill level for those skills, with the employee name as a last resort, so that I can easily identify employees with the most relevant and advanced skillsets.

Acceptance criteria:
 - [x] The "Team Skills" report results are initially sorted by the number of matching skills for the selected criteria, in descending order.
 - [x] When multiple employees have the same number of matching skills, the results are then sorted by the average skill level for those skills, in descending order.
 - [x] Finally, if multiple employees have the same number of matching skills and the same average skill level, they are sorted alphabetically by name.

**Comment by mvolkmann** [comment]
The second acceptance criteria says "average skill level". The current implementation (in the PR) uses the sum of the skill levels. This will result in the same sorting since this criteria only comes into play when the employees have the same number of skills.

**Comment by mvolkmann** [comment]
I believe this story is handled by the PR for 2112. @S78901 is this correct?
