### ISSUE TITLE
Date pickers missing for feedback request

### ISSUE THREAD

**Issue by pieperm** [objectcomputing/check-ins#2157]
**Describe the bug**
When creating a feedback request, the date pickers for send date and due date do not appear on the page.

**To Reproduce**
1. Create a feedback request for any member
2. Progress to step 3: Set dates
3. No date pickers appear on the page

**Expected behavior**
There should be two date pickers on the set dates step.

**Screenshots**
![feedback-request-bug](https://github.com/objectcomputing/check-ins/assets/14118066/bac5a594-72f9-4966-a058-090a028de257)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox

**Additional context**
The error in the console is:
```
MUI: The MobileDatePicker component was moved from `@mui/lab` to `@mui/x-date-pickers`.

You should use `import { MobileDatePicker } from '@mui/x-date-pickers'`
or `import { MobileDatePicker } from '@mui/x-date-pickers/MobileDatePicker'`

More information about this migration on our blog: https://mui.com/blog/lab-date-pickers-to-mui-x/. 
```

**Comment by mkimberlin** [comment]
@S78901 I think I fixed this with PR #2156
