### ISSUE TITLE
Select Review Templates via Dropdown

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2163]
As a platform Admin, I want to select the Review and Self-Review templates from dropdown lists when creating a new review period, so that I can easily choose the appropriate templates without needing to remember template IDs.

## Acceptance Criteria
 - [x] When creating a new review period, dropdown lists labeled "Review Template" and "Self-Review Template" are displayed.
 - [x] The dropdown lists contain all available review templates (templates for which `isReview` is true) listed by name Alphabetically.
 - [x] Selecting a template from a dropdown populates the appropriate template ID field with the corresponding ID for that template.
 - [x] The template IDs are stored with the new review period appropriately upon saving the review period.

**Comment by mvolkmann** [comment]
FeedbackTemplateResponseDTO does not include data from the `is_review` column in the feedback_templates table, so I can't verify in the UI code that `isReview` is true.
