### ISSUE TITLE
Enhanced Check-Ins Report

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2212]
Depends on #2211

**As an** Admin
**I want** a more informative Check-In report to track the completion of quarterly meetings with PDLs
**So that** I can easily identify PDLs who have completed, scheduled, or not started their Check-Ins.

## Acceptance Criteria:

 - [ ] The existing "Check-Ins" report will be replaced with a new report with the following functionalities:
   - [ ] Utilize the `MemberSelector` component to allow selecting PDLs.
   - [ ] By default, the report will automatically select all PDLs.
 - [ ] The report will list each selected PDL.
 - [ ] Each PDL will be displayed in an expandable section with a summary. This summary will include:
   - [ ] PDL's avatar, name, and title.
   - [ ] A status indicator for their assigned Check-Ins:
     - [ ] "Done": If the PDL has held and completed Check-Ins for all assigned team members in the current quarter.
     - [ ] "In Progress": If the PDL has any Check-Ins scheduled for the current quarter.
     - [ ] "Not Started": If the PDL has not scheduled or completed any Check-Ins for the current quarter.
 - [ ] Users should be able to select the quarter for which they want to run the report.
 - [ ] During the first month of a new quarter, the report will default to showing data for the previous quarter as the "current quarter". It will only switch to the new quarter after a full month has passed.

**Comment by vhscom** [comment]
All ACs now covered and this story can be closed once we've done a little UAT.

**Comment by vhscom** [comment]
Spawns: https://github.com/objectcomputing/check-ins/issues/2425
