### ISSUE TITLE
Replace isOpen with status

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2217]
**As an Administrator**, I want the `isOpen` field for review periods to be converted to an enumeration field named `status` with potential values `Planning`, `Awaiting Approval`, `Open`, and `Closed` **so that** I can easily understand and manage the workflow of each review period.

## Acceptance Criteria
- [ ] The isOpen field on the ReviewPeriod model is removed.
- [ ] A new field named status of type enumeration is added to the ReviewPeriod model with the following allowed values: Planning, Awaiting Approval, Open, and Closed.
- [ ] Existing data is migrated such that true in the isOpen field becomes Open in the new status field and false becomes Closed.

**Comment by mjperry91** [comment]
https://github.com/objectcomputing/check-ins/pull/2273

**Comment by S78901** [comment]
@mjperry91 Please let me know once this is merged so I can finalize Issue #2220.
