### ISSUE TITLE
Restrict review period state transitions

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2218]
Depends on #2217.

**As an Administrator**, I want the API for managing review periods to enforce the allowed progressions between review period states (Planning -> Awaiting Approval -> Open -> Closed) **so that** I can't accidentally transition a review period to an invalid state.

## Acceptance Criteria
- [ ] The API endpoints for updating the status field of a ReviewPeriod should restrict updates to only allowed transitions based on the current state.
- [ ] Progression between states can only move forward, except `Closed` which can be re-opened.

**Comment by mvolkmann** [comment]
@mkimberlin In the current UI, how does the user cause a review period to transition to a new state?

**Comment by mkimberlin** [comment]
> @mkimberlin In the current UI, how does the user cause a review period to transition to a new state?

There isn't such a concept in the current UI. There is only Open or Closed (Archived).

**Comment by ZacharyKlein** [comment]
@timyates This might be a good story for you to pick up next. I think we need to implement a simple state machine based on the previous work in https://github.com/objectcomputing/check-ins/issues/2217
