### ISSUE TITLE
Create review status stepper component

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2220]
**As an Administrator**, I want a stepper component to be created that displays the current status of a review period **so that** I can easily see the current stage of the review process.

## Acceptance Criteria:

- [x] A new React component utilizing Material UI's stepper component (https://mui.com/material-ui/react-stepper/) is created.
- [x] This component takes the status of a review period as a prop.
- [x] The component displays the current status visually using the stepper functionality.
- [x] The component supports the progression of statuses defined in #2217

**Comment by S78901** [comment]
<img width="384" alt="Screenshot 2024-05-03 at 11 58 22 AM" src="https://github.com/objectcomputing/check-ins/assets/39834839/7f5ac394-7fb9-4178-86c8-20e5709d8271">
