### ISSUE TITLE
Enable storing review period timelines

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2227]
**As an Administrator**, I want the API for storing review periods to be altered to allow for saving the planned timeline for the review period **so that** we can appropriately plan and track review periods.

## Acceptance Criteria:
 - [ ] The data structures returned and accepted by the review period APIs are altered to include the following new fields:
   - [ ] launchDate
   - [ ] selfReviewCloseDate
   - [ ] closeDate

**Comment by mjperry91** [comment]
PR: https://github.com/objectcomputing/check-ins/pull/2239

**Comment by mjperry91** [comment]
Quick test adding reviews with a template

![New Review Periods](https://github.com/objectcomputing/check-ins/assets/97112306/60fbc79e-1aae-4484-b30e-701e405e30c9)

We can see the reviews were added successfully, and current defaults for launchDate, selfReviewCloseDate, and closeDate are null.

![Review Periods In Database](https://github.com/objectcomputing/check-ins/assets/97112306/de7e245a-c5cb-466c-8694-202f165e5682)

@mkimberlin Do we have follow on stories for UI updates where these new values will be set?

**Comment by mkimberlin** [comment]
> @mkimberlin Do we have follow on stories for UI updates where these new values will be set?

Yes, but for now we just want to adjust to keep functionality the same. I don't have a story written for that. I can throw one together right after this meeting.

**Comment by S78901** [comment]
Added console logs to https://github.com/objectcomputing/check-ins/pull/2277 illustrate the API receiving the date for these fields as a string and returning it as a serialized array that can't be utilized. @mjperry91 for your review:

Input:
launchDate: "2024-05-03T05:00:00.000Z"

API returns:
[
2024,
5,
3,
5,
0
]

**Comment by mjperry91** [comment]
> Added console logs to #2277 illustrate the API receiving the date for these fields as a string and returning it as a serialized array that can't be utilized. @mjperry91 for your review:
> 
> Input: launchDate: "2024-05-03T05:00:00.000Z"
> 
> API returns: [ 2024, 5, 3, 5, 0 ]

https://github.com/objectcomputing/check-ins/pull/2327
