### ISSUE TITLE
Allow planning review period timeline

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2228]
Depends on #2227.

**As an Administrator**, I want a calendar component to be integrated into the review period dashboard for periods in the `Planning` state **so that** I can define the review period timeline. This part of the UI is under FEEDBACK ... Reviews ... ADD REVIEW PERIOD.

## Acceptance Criteria:

 - [x] A calendar component (modal?) is implemented and integrated into the dashboard for review periods in the `Planning` state.
 - [x] The calendar is displayed automatically if the review period is in the `Planning` state and does not yet have values for the managed target dates.
 - [x] A summary listing the planned timeline is shown if the managed target dates already have values.
 - [x] This calendar allows the administrator to set the following dates:
   - [x] Launch Date
   - [x] Self-Review Close Date
   - [x] Review Period Close Date
 - [x] APIs to update the review period with these dates are called once the dates have been selected and confirmed (see #2227)

**Comment by mkimberlin** [comment]
I have a clarifying point on this story...replace anywhere it says "Administrator" with "user that has `CAN_UPDATE_REVIEW_PERIOD`" or whatever permission comes out of #2223. It might be worthwhile to see if we can find someone to attend to that story sooner than later.

**Comment by S78901** [comment]
For Planning status:
<img width="1410" alt="Screenshot 2024-05-06 at 4 56 30 PM" src="https://github.com/objectcomputing/check-ins/assets/39834839/9858ee2f-375f-4ac6-893e-5a103eac97db">
