### ISSUE TITLE
Change access to Download Members

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2242]
**As a User with the "CAN_VIEW_PROFILE_REPORT" permission**, I want to download a list of all members **so that** I can analyze member data.

Acceptance Criteria:
- [x] The user interface for the ADMIN -> Users page should now include a download icon button with alt text labeled "Download Members".
- [x] Users that do not have the "CAN_VIEW_PROFILE_REPORT" permission should not see the "Download Members" button on the ADMIN -> Users page.
- [x] Clicking the "Download Members" button should initiate a download of a CSV file containing a list of all members. (Currently initiated by clicking the menu item on the menu initiated by clicking one's own avatar.)
- [x] The "Download Members" option should no longer appear in the avatar menu.

**Comment by mvolkmann** [comment]
finished
