### ISSUE TITLE
Keep context in URL: View Feedback

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2268]
**As an Administrator**, I want the URL for the view feedback page to include contextual information **so that** I can refresh the page without losing my selection.

## Acceptance Criteria:

 - [x] The URL should include a parameter search with the value of the search string entered in the search bar (if any).
 - [x] The URL should include a parameter with the value the show all toggle.
 - [x] The URL should include a parameter with the value of the "Show requests sent within" dropdown
 - [x] The URL should include a parameter with the value of the "Sort by" dropdown
 - [x] Refreshing the page with any of these parameters in the URL should maintain the previously selected context on the page

**Comment by mvolkmann** [comment]
I accidentally did this work in the feature-2265-team-directory-query-parameters branch.
