### ISSUE TITLE
Alter the Guild service to allow distinguishing communities from guilds

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2286]
**As an administrator,** I want to add a flag to guild services that indicates whether a guild is a community **so that** we can categorize and manage guilds based on their purpose.

## Acceptance Criteria:
 - [ ] The guild table is extended to include a new boolean field named `community`.
 - [ ] Necessary data objects representing guilds (entities, dtos, etc) should be altered to contain an boolean field to store this value.
 - [ ] The guild creation API endpoint allows specifying a value for the `community` flag during guild creation.
 - [ ] Existing guild management APIs are updated to allow modifying the `community` flag for existing guilds.
 - [ ] The guild retrieval APIs (e.g., by ID or search) include the `community` flag in the returned guild information.

**Comment by mjperry91** [comment]
https://github.com/objectcomputing/check-ins/pull/2312
