### ISSUE TITLE
Allow managers to confirm review assignments

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2292]
**As a Manager**, I want to be able to review the reviewer assignments for my team **so that** I can ensure they are accurate and approve them.

## Acceptance Criteria:

 - [x] If a user that is a manager enters the review period dashboard for a review period that is in `Awaiting Approval` state it should bring up a page displaying the timeline of the review period and the review assignments for that manager's direct reports.
 - [x] This page should include at minimum:
   - [x] A "Show All" Checkbox that allows the manager to view not only their direct reports, but all of the employees reporting to them (even if they report directly to another manager in their heirarchy)
   - [x] A search field that allows the manager to find a specific employee by name.
   - [x] A list of each employee reporting to the manager.
   - [x] The name of the currently assigned reviewer for each employee.
   - [x] A button or action item of some sort for each assignment that allows the manager to approve that assignment
   - [x] A button labeled "Approve All" that:
     - [x] Initiates a confirmation dialog that transitions all of the managers review assignments currently in view to the approved state.

**Comment by mkimberlin** [comment]
I used a bit of shorthand for some functionality in this. If we need to flush it out more, I am happy to do so.

**Comment by mvolkmann** [comment]
@mkimberlin The first AC says "should bring up a page displaying the timeline of the review period". Can the manager edit the dates from this page or only view them?

**Comment by mvolkmann** [comment]
@mkimberlin Can review assignments be modified in this page or only approved?

**Comment by mvolkmann** [comment]
@mkimberlin It's not clear how I can determine if the current user is a manager. From what I see we only support three roles: ADMIN, PDL, and MEMBER. Do you know I can detect a manager?

**Comment by mkimberlin** [comment]
> [@mkimberlin](https://github.com/mkimberlin) The first AC says "should bring up a page displaying the timeline of the review period". Can the manager edit the dates from this page or only view them?

If they have permission to modify the review cycle, then it can be modified. If they don't, then it should only be viewable.

> [@mkimberlin](https://github.com/mkimberlin) Can review assignments be modified in this page or only approved?

If they have permission to modify the review cycle, then they can be modified. If they don't, then they should only be approvable.

> [@mkimberlin](https://github.com/mkimberlin) It's not clear how I can determine if the current user is a manager. From what I see we only support three roles: ADMIN, PDL, and MEMBER. Do you know I can detect a manager?

There is a selector called `selectSupervisors`.

**Comment by mvolkmann** [comment]
Thanks @mkimberlin! There is so much similarity between this new page and the page implemented by TeamReviews.jsx that I'm thinking I should find a way to add the new function in that file. How do you feel about that?
