### ISSUE TITLE
Keep context in URL: Team Skills Report

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2309]

**Comment by mvolkmann** [comment]
@mkimberlin I can easily maintain the selected skills in a query parameter. But I'm wondering if it makes sense to also maintain the selected members in a query parameter. The value would be a comma-separated list containing the ids of all the selected members. It could be quite long. Do you think I should do that?

**Comment by mkimberlin** [comment]
@mvolkmann hash parameters may be better suited, now that you mention that. Query parameters won't work if it gets too long.
