### ISSUE TITLE
FEEDBACK ... Reviews error on initial page load

### ISSUE THREAD

**Issue by mvolkmann** [objectcomputing/check-ins#2320]
**Describe the bug**

Click "FEEDBACK" in the left nav. and then click "Reviews". You will see a red error box that says "Null value read for non-null constructor argument [launchDate] of type: com.objectcomputing.checkins.services.reviews.ReviewPeriod"

**To Reproduce**

1. Click "FEEDBACK" in the left nav.
2. Click "Reviews"

**Expected behavior**

This error should not occur.

**Screenshots**

![Screenshot 2024-05-02 at 11 13 39 AM](https://github.com/objectcomputing/check-ins/assets/79312/618bbb54-9bdf-492c-97b2-8060c2eaa0df)

**Comment by mjperry91** [comment]
https://github.com/objectcomputing/check-ins/pull/2322
