### ISSUE TITLE
Implement initial Pulse Survey UI

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2347]
**As a Team Member** I want to be able to provide my feelings about work and life outside of work, **so that** my manager understands my needs.

This story depends on the server story #2345.

## Acceptance Criteria:
 - [x] The page linked to the "Pulse" submenu should be adjusted as follows:
  - [x] The page should display separate prompts for internal and external feelings with a scale of 1 to 5 for each.
    - [x] The response options should be displayed as a scale along with colored indicators from Red (1) to Green (5) creating a gradient of colored indicators similar to: 🔴 🟠 🟡 🔵 🟢  or similar (maybe a light green instead of blue?)
  - [x] Below each prompt, an optional text field should be provided for comments.
  - [x] A "Submit" button should be available on the page.
  - [x] Pressing the "Submit" button should save the responses via the pulse response API.
  - [x] Upon successful submission for a given day, the input fields and comment box should become disabled until the next day.
- [x] Any resulting components should be represented in with component stories
- [x] Any resulting components should have appropriate unit tests

**Comment by mvolkmann** [comment]
@mkimberlin Do you prefer colored circles over faces like these?
![faces](https://github.com/objectcomputing/check-ins/assets/79312/21b24aa6-f917-4c3a-981c-e9d7b0293f8d)
