### ISSUE TITLE
Create a service for manipulating settings values

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2355]
**As a System Administrator**, I want REST services to manage setting values, **so that** I can configure the application's behavior through the API.

## Acceptance Criteria:
 - [x] A new table named "settings" should be created in the database schema.
 - [x] The "settings" table should have these columns:
   - [x] `name` (VARCHAR, PRIMARY KEY, UNIQUE): Name of the setting, corresponding to an option contained in the settings enum.
   - [x] `value` (TEXT): The current value for the setting.
 - [x] A migration script should be created to alter the database schema and add the "settings" table.
 - [x] The following services should be implemented:
   - [x] A GET endpoint at `/services/settings` should retrieve all setting name-value pairs from the database.
   - [x] A PUT endpoint at `/services/settings/{name}` should allow updating the value for a specific setting.
     - [x] The request body should contain the new value as JSON data.
 - [x] Error handling should be implemented to return appropriate status codes for successful and unsuccessful requests.
   - [x] Attempting to store values that do not have an associated value in the settings enum should result in an bad request error.
   - [x] A new permission called `CAN_ADMINISTER_SETTINGS` should be created and used for protecting both of these new endpoints.

**Comment by jackkeller** [comment]
@mkimberlin is there an idea of the different settings that we'll want to have control over? Mainly asking to anticipate what we'll be needing on the #2356 side of things.

**Comment by mkimberlin** [comment]
I think there are a few categories of settings we will likely see out of the gate; one could be theming-related settings potentially (logo, primary/secondary/tertiary colors, etc.), another could be enabling and configuring various integrations (mailjet for example), and there might be some other values from our `run.sh` script variables that would be better served as admin configurable.

**Comment by mjperry91** [comment]
@mkimberlin since the PUT endpoint requires us to pass a valid setting object to it, I have left this endpoint as `/services/settings` instead of adding the name path variable as we can just get that from the object and also verify the ID.

**Comment by mjperry91** [comment]
PR: https://github.com/objectcomputing/check-ins/pull/2405
