### ISSUE TITLE
Implement pulse survey report

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2357]
**As a Team Member (with appropriate permission)**, I want to view a report on pulse survey data **so that** I can be attentive to the needs of those in the organization.

## Acceptance Criteria:
 - [x] A new report page for pulse survey data should be created.
 - [ ] This page should only be accessible to those with access to the data (see the related service story)
   - [ ] A user with "CAN_VIEW_ALL_PULSE_RESPONSES" permission
   - [ ] A manager
 - [x] The report should have clearly labeled start and end date fields allowing users to specify a date range.
   - [x] By default, the report should display data for the last 3 months.
 - [x] The report should include a `MemberSelector` component to choose which team members' data to include.
   - [ ] If the user does not have "CAN_VIEW_ALL_PULSE_RESPONSES", the `MemberSelector` should limit them to only those under them in the reporting hierarchy and default to selecting their direct reports
   - [ ] If the user does have "CAN_VIEW_ALL_PULSE_RESONSES", then default to selecting all employees.
 - [x] Display a card with a line graph showing the average pulse score for "At Work" (internalFeelings) and "Outside Work" (externalFeelings) responses over the selected date range and people.
 - [x] Display a card with a bar graph showing the distribution of pulse scores for the selected people and date range.
   - [x] The card should be expandable to show a list of individual responses for the selected period and filter. Each entry should include:
     - [x]  Avatar of the person who submitted the response.
     - [x] Name of the person who submitted the response.
     - [x] Title of the person who submitted the response (optional).
     - [x] Numerical value of the submitted pulse score.
     - [x] An icon indicating if a comment was submitted with the response.
       - [x] Clicking the comment icon displays the submitted comment in a modal window.

**Comment by mvolkmann** [comment]
@mkimberlin For the line chart I assume we want dates across the x-axis and scores (1-5) across the y-axis. Since everyone won't report their pulse every day, we will have to make some assumptions. How about these?
- If a person hasn't reported pulse scores (internal and external) for a given day, we will assume they are the same as the previous day for which they reported scores.
- If there is no previous score, we will assume scores of "satisfied" (4 out of 5).
These assumptions will allow us to compute an average score for all selected members for any day.

**Comment by mvolkmann** [comment]
@mkimberlin For the bar chart I assume we want team members across the x-axis and average scores over the selected date range across the y-axis. Correct?

**Comment by mkimberlin** [comment]
> @mkimberlin For the line chart I assume we want dates across the x-axis and scores (1-5) across the y-axis. Correct?
> 
> Since everyone won't report their pulse every day, we will have to make some assumptions. How about these?
> 
> * If a person hasn't reported pulse scores (internal and external) for a given day, we will assume they are the same as the previous day for which they reported scores.
> * If there is no previous score, we will assume scores of "satisfied" (4 out of 5).
>   These assumptions will allow us to compute an average score for all selected members for any day.

WRT the x and y axis, you are correct.

I don't want to assume anything about scores. I want to give the average for the scores that we have. If a day has 5 responses, we add those up and divide by 5. If a person didn't respond, they simply don't get included in that calculation.  If we don't have any responses for a given day, then we don't plot a point for that day.

> @mkimberlin For the bar chart I assume we want team members across the x-axis and average scores over the selected date range across the y-axis. Correct?

I want a bar on the x axis for each possible score (1-5) with the y-axis being the number of responses.

So you would see that X people responded with a 1 and Y people with a 2 and so on...
