### ISSUE TITLE
(Backend) - Refactor Existing Blocking Controllers to Non-Blocking Using Project Reactor

### ISSUE THREAD

**Issue by mjperry91** [objectcomputing/check-ins#2372]
- We have multiple pre-existing controllers that are implemented in a blocking manner. This story will update those controllers to be non-blocking inline with the vast majority of other check-in controllers.

Blocking Controllers
-  [x] ActionItemController
-  [ ] CheckinNoteController
-  [ ] GuildMemberController
-  [ ] CurrentUserController
-  [ ] MemberRoleController
-  [ ] TeamMemberController

**Comment by sdelamo** [comment]
I think we can closed this via https://github.com/objectcomputing/check-ins/pull/2418

**Comment by mjperry91** [comment]
> I think we can closed this via #2418

Agreed. I coordinated this with @S78901 this morning after seeing your PRs.

**Comment by mjperry91** [comment]
We can move to jdk 21 and use virtual threads for these endpoints, which will give us non-blocking functionality without having to use reactor. This will be address in another issue.
