### ISSUE TITLE
Add Highest Scores chart to pulse report

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2416]
**As a user with access to the pulse response report**, I want to see charts showing the highest and lowest average scores **so that** I can easily identify the most and least satisfied team members based on average scores from the selected time range.

### Highest Scores Chart

 - [x] The highest scores chart should be titled "Highest Average Scores".
 - [x] There should be a toggle feature allowing the user to switch between "Individual" and "Manager" views.
 - [x] When in "Individual" mode:
   - [x] Display the highest 5 average scores of individuals for the selected time range.
   - [x] Each entry should include:
     - [x] A small avatar for the user.
     - [x] The user’s full name.
     - [x] The user’s title.
     - [x] The user’s average score.
 - [x] When in "Manager" mode:
   - [x] Display the highest 5 average scores for the employees of managers for the selected time range.
   - [x] Each entry should include:
     - [x] A small avatar for the manager.
     - [x] The manager’s full name.
     - [x] The manager’s title.
     - [x] The average score of the manager's employees for the selected time range.
 - [x] The chart should dynamically update based on the settings (time range, etc.) selected in the report.
 - [x] The average scores should be calculated from the pulse responses within the selected time range.

You can use the following as a basic mockup:

![Image](https://github.com/objectcomputing/check-ins/assets/100510/8788bb94-18dc-4dfd-8443-7b314735a522)

### Lowests Scores Chart

 - [x] The lowest scores chart should be titled "Lowests Average Scores".
 - [x] There should be a toggle feature allowing the user to switch between "Individual" and "Manager" views.
 - [x] When in "Individual" mode:
   - [x] Display the lowest 5 average scores of individuals for the selected time range.
   - [x] Each entry should include:
     - [x] A small avatar for the user.
     - [x] The user’s full name.
     - [x] The user’s title.
     - [x] The user’s average score.
 - [x] When in "Manager" mode:
   - [x] Display the lowest 5 average scores for the employees of managers for the selected time range.
   - [x] Each entry should include:
     - [x] A small avatar for the manager.
     - [x] The manager’s full name.
     - [x] The manager’s title.
     - [x] The average score of the manager's employees for the selected time range.
 - [x] The chart should dynamically update based on the settings (time range, etc.) selected in the report.
 - [x] The average scores should be calculated from the pulse responses within the selected time range.

You can use the following as a basic mockup:

![Image](https://github.com/objectcomputing/check-ins/assets/100510/8306459a-9cbe-4427-9fca-07bf3c9b21d9)

**Comment by mvolkmann** [comment]
@mkimberlin For computing the average scores, should it combine the internal and external scores?
Maybe I should add a drop that lets the user choose between "Internal Scores", "External Scores", and "Both Scores".

**Comment by mkimberlin** [comment]
A toggle would be good, I think.
