### ISSUE TITLE
Check-Ins Report Member Filtering

### ISSUE THREAD

**Issue by vhscom** [objectcomputing/check-ins#2425]
**Given** an Admin is viewing Check-in Report
**When** the report contains members no longer with the company
**Then** the report takes into consideration the termination date

## Given:

It is not current practice to change a member's assigned PDL upon termination.

## Acceptance Criteria:

- [ ] Report will continue to list PDLs with a `terminationDate` during the current quarter
  - [ ] The PDL termination date captured in the PDL's member profile is displayed in the report summary card
  - [ ] ~~The overall status of the Quarter's Check-Ins for that PDL will be "Unavailable" unless already "Done"~~
  - [ ] <ins>The overall status for a terminated PDL will be `Terminated`</ins>
  - [ ] <ins>Terminated PDLs will sort below PDLs without members at the bottom of the list
- [ ] Report will not list PDLs with a `terminationDate` in the current or any future quarter
- [ ] Report will <ins>_not_ continue to</ins> list PDL Dev Partners with a `terminationDate` during the current quarter
  - [ ] ~~Report will continue to list terminated PDL Dev Partners with a `terminationDate` in any previous quarter~~
- [ ] The overall PDL status will reflect progress during the current quarter based only on actively-employed members
- [ ] The badge reflecting the number of members assigned to a PDL should exclude terminated members

**Comment by vhscom** [comment]
This item is marked [review] for another pair of eyes.

**Comment by mkimberlin** [comment]
"Report will not list PDLs with a non-null terminationDate in any previous quarter"
I think this is backward. I think we don't want to show them for future quarters. If they were an active PDL in a previous quarter, we would want to be able to see them in the report.

**Comment by mkimberlin** [comment]
"Report will not list PDL Dev Partners with a terminationDate who are no longer assigned to a PDL"
I think the second part of that condition is irrelevant. The data will likely still have them assigned to a PDL, as we don't remove those values on termination currently. If they have a termination date prior to the beginning of the current quarter, they shouldn't show up.

**Comment by mkimberlin** [comment]
> The overall PDL status will reflect progress during the current quarter based only on actively-employed members

This is good thinking. I'm not sure I would have thought of this until I ran into a case that confused me. 👍 

> The badge reflecting the number of members assigned to the PDL will not change until the member is unassigned

I actually think I would only reflect active assignments. If they are terminated, I would rather not see them in that number because it's primarily used to determine whether a PDL has the bandwidth for another assignment...and if that person has moved on, they do.
