### ISSUE TITLE
Tracking Certifications

### ISSUE THREAD

**Issue by mikeklop1979** [objectcomputing/check-ins#2446]
As an administrator, I want the ability to track certifications. The certification tracking will be similar to current functionality of tracking skills. 

Acceptance Criteria:
⦁	An optional URL will appear for user's to select the applicable certifications.
⦁	The certification entry will appear on the user's profile page. 
⦁	The user inputs the data, not the administrator.
⦁	 When the training certification data is inserted it will go into a "pending" status for administrators. Admin's will then move it to "approved" to keep the process and certifications organized.
⦁	Once "approved", the certifications will be displayed on the user's profile page. 
⦁	Certifications will be grouped by vendor (AWS, Google)

**Comment by mvolkmann** [comment]
Michael agreed to forego the "pending" and "approved" states for now. Certifications created by users will be immediately visible.
