### ISSUE TITLE
Pulse Manager Report

### ISSUE THREAD

**Issue by mikeklop1979** [objectcomputing/check-ins#2465]
From the pulse feedback scores, create an email that goes to the Manager and PDL from the pulse survey member/user.

Acceptance Criteria:

- Email notification to the Manager and PDL that has a score of 2 or less.
- Email to the Manager & PDL will state the score and a note to consider reaching out to the member/user.

**Comment by chrismckiernan** [comment]
https://github.com/objectcomputing/check-ins/pull/2480
