### ISSUE TITLE
Self-Review Notifications

### ISSUE THREAD

**Issue by mikeklop1979** [objectcomputing/check-ins#2474]
**As a user that is part of a performance review**, I want to have effective notifications and reminders that I need to perform a self-review, **so that** the process can proceed smoothly.

## Acceptance Criteria
 - [ ] When the launch date of an *OPEN* review period has been reached, an email should be sent to each of the team members included in the review period notifying them that it is time to begin their self-review.
 - [ ] Three days before the self-review completion date of an *OPEN* review period, an email will be sent to each of the team members who are included in the review period reminding them to complete their self-review.
 - [ ] One day before the self-review completion date of an *OPEN* review period, an email will be sent to each of the team members who are included in the review period reminding them to complete their self-review.

**Comment by mkimberlin** [comment]
[Self-Review Reminder.mjml.zip](https://github.com/user-attachments/files/17346213/Self-Review.Reminder.mjml.zip)
