### ISSUE TITLE
BUG: File upload fails on checkins page

### ISSUE THREAD

**Issue by rodecapd** [objectcomputing/check-ins#2514]
**Describe the bug**
Uploading a file on the checkins page results in an HTTP 400 error

**To Reproduce**
1. log in as a user with a PDL assignment
1. Create a Check in
1. In the Documents section, click "Upload a document"
1. Choose a document.
1. The upload fails with a HTTP 400 error:
<img width="1350" alt="image" src="https://github.com/objectcomputing/check-ins/assets/97561243/dce82b4e-78b4-4084-9483-fcf1bc7fa5d0">

**Expected behavior**
Expected document to upload successfully:
<img width="1637" alt="image" src="https://github.com/objectcomputing/check-ins/assets/97561243/0bd22d1d-13bc-4f07-91fa-b5f3235a7cf7">

**Desktop (please complete the following information):**
 - OS: 

**Smartphone (please complete the following information):**
 - Device: Macbook Pro
 - OS: Sonoma 14.5
 - Browser: Chrome
 - Version: 125.0.6422.77 (Official Build) (x86_64)

**Comment by rodecapd** [comment]
Tested in checkins-dev.  Verified upload, download and delete.

**Comment by timyates** [comment]
Newbie question, how do I `log in as a user with a PDL assignment`?

I cannot see the Documents section under any of the Check-ins pages 😞
