### ISSUE TITLE
Skills Report not working for non admins

### ISSUE THREAD

**Issue by oschwaldp-oci** [objectcomputing/check-ins#2535]
**Describe the bug**
Skills Report not working for non admins

**To Reproduce**
1. Go to https://checkins.objectcomputing.com/skills-reports
2. nothing populates on page

**Expected behavior**
Not sure exactly what it is supposed to look like, but more than a blank page I'm hoping.

**Screenshots**
Attached
![CheckIns-BlankSkillsReport](https://github.com/objectcomputing/check-ins/assets/11048242/59119343-c258-4067-9d07-a9259335903b)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mkimberlin** [comment]
@ocielliottc adjust it to respect the appropriate permissions and not the admin role
