### ISSUE TITLE
Review Launch Notification

### ISSUE THREAD

**Issue by mikeklop1979** [objectcomputing/check-ins#2543]
In the review process, a notification to applicable team members is not occurring. 

Expected behavior:

When a "launch review" occurs, Check-Ins should notify everyone in the process and it is currently not doing those notifications.

**Comment by mkimberlin** [comment]
To be clear, this email should go out when the review is transitioned to "Open".

[ReviewPeriod-Announcement.mjml.zip](https://github.com/user-attachments/files/17192348/ReviewPeriod-Announcement.mjml.zip)
