### ISSUE TITLE
Recategorize "Impersonate organization members"

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2573]
Move the "Impersonate organization members" permission to the "Security" category.

## Acceptance Criteria
When viewing the Permission management page (ADMIN -> Permissions) as a user that has permission to view all permissions:
  - [ ] The permission labeled "Impersonate organization members" is no longer listed under the "User Management" category.
  - [ ] The permission labeled "Impersonate organization members" is listed under the "Security" category.

**Comment by ocielliottc** [comment]
You know, I considered whether that should go under Security or not!
