### ISSUE TITLE
Self-Review Email sent to Supervisor/PDL - Include link to review

### ISSUE THREAD

**Issue by Luch76** [objectcomputing/check-ins#2595]
When a self-review is completed, an email is sent to the reviewee's PDL and supervisor. Using method FeedbackRequestServicesImpl.sendSelfReviewCompletionEmailToPdlAndSupervisor

It currently contains this text in body: 
>>>>>>
Self-review has been completed by Lucky Bear for Luch 2024-09-17 11:48.
PDL: Mischievous Kangaroo
Supervisor: Big Boss

It is now your turn in their review process. Please complete your portion in a timely manner.
<<<<

Add an additional line: A link to the self-review

**Comment by mkimberlin** [comment]
If you use the templates I added on #2595 then you'll need to implement this in the context of that.

**Comment by mkimberlin** [comment]
Actually, I'm going to close this in favor of that issue.
