### ISSUE TITLE
Self-Review Email (to supervisor/PDL and reviewers) - Send in MJML format

### ISSUE THREAD

**Issue by Luch76** [objectcomputing/check-ins#2596]
When a self-review is completed, two emails are sent out. An email is sent to the reviewee's PDL and supervisor using method FeedbackRequestServicesImpl.sendSelfReviewCompletionEmailToPdlAndSupervisor and to the reviewers using method: FeedbackRequestServicesImpl.sendSelfReviewCompletionEmailToReviewers

Modify these emails so they are sent in MJML format. 

Reference: 
https://github.com/mjmlio/mjml
https://mjml.io/api

**Comment by mkimberlin** [comment]
[mjmltemplates.zip](https://github.com/user-attachments/files/17191974/mjmltemplates.zip)

**Comment by ocielliottc** [comment]
@mkimberlin Currently, an email is sent to the pdl and supervisor.  There is only a supervisor template.  Should the pdl still receive an email?  If so, use the supervisor template?
