### ISSUE TITLE
Calculate Approval completion by Supervisor

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2620]
**As a user participating in the administration of review periods**, I would like to be able to see the percentage of review assignment approval completions by Supervisor rather than by Review Assignee **so that** I know who to talk to about approving the remaining assignments.

## Acceptance Criteria

- [ ]  Percentage breakdowns on the review periods page should be by Supervisor, rather than by review assignee

### Current State
In the screenshots shown below, you'll notice that Mischievous Kangaroo shows at 50% and Crazy Elephant at 100%. In the desires state, Mischievous Kangaroo would have shown 100% and Crazy Elephant would not be listed at all (they are not a supervisor)

![Screenshot 2024-10-07 at 9 06 30 AM](https://github.com/user-attachments/assets/53a4d672-a235-45d7-a7db-c5634645df2a)
![Screenshot 2024-10-07 at 9 06 42 AM](https://github.com/user-attachments/assets/6a13bee7-a50d-4593-86d1-d801be9bf6d5)

**Comment by ocielliottc** [comment]
@mkimberlin I implemented this assuming that if a reviewer is not a supervisor, use their supervisor as the member to include in the approval statistics calculation.  Does that sound right to you?

**Comment by mkimberlin** [comment]
@ocielliottc it should reflect the percentage of review assignments that exist for each manager's subordinates that have been approved. So one implementation could be:

* Loop though the assignments and for each: 
   * Get the manager id from the profile of the person being reviewed and create a map entry that contains counters for approved and total reviews (or use an already created one)
   * Increment those counters as appropriate for each assignment 
 * Use those map entries to display the calculated percentage for each supervisor that has an entry

**Comment by ocielliottc** [comment]
@mkimberlin Ok.  I think I understand.  I think I can use what I have, but use the reviewee supervisor (instead of the reviewer's supervisor).
