### ISSUE TITLE
Reviews - Removing & Adding User bug - removed user isn't removed

### ISSUE THREAD

**Issue by Luch76** [objectcomputing/check-ins#2636]
Have a Review with one user. Goto list to add/remove members. Add a new member, and remove the original user that was there. You'll then see the user that was removed is still there. 

Note the bug doesn't happen when you have multiple users, and simply remove one user

**Comment by ocielliottc** [comment]
So, what happens is that when you remove and add in one shot, it only locally removes the reviewers and does a POST to add the new ones.  What you get back is the full list of reviewers from the server.  This will just require me to add some code to DELETE the reviewers.
