### ISSUE TITLE
Managers can't approve assignments

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2654]
I'm not sure exactly what is causing this...but it seems that users configured to be able to update, view, create, and delete review assignments can't do so. This is preventing managers from being able to approve their team's review assignments.

They also should not see their own review assignment or those that belong to other managers.

![Screenshot 2024-10-22 at 9 22 11 AM](https://github.com/user-attachments/assets/9f077b5d-422b-4706-bb44-1c1d0f00646e)

**Comment by mkimberlin** [comment]
@ocielliottc that permission should be used to limit edits made to the review period itself (who is included in the review, the dates, the launch status, etc). However, every manager will need the ability to add, remove or update review assignments...and I'll be creating a manager role with those permissions. I would make the add button depend on the create_review_assignments permissions (not sure about these names, but you'll get the idea), the remove button depend on delete_review_assignments, and the approve button(s) depend on the update_review_assignments permission.

**Comment by ocielliottc** [comment]
@mkimberlin Since, in the dialog that comes up when hitting the "plus" button, the user can add or remove reviewers, I think the button should require both create and delete permissions.  Right?

**Comment by mkimberlin** [comment]
@ocielliottc ideally, I think we would make that member selector limit their ability to remove existing assignments if they didn't have the delete permission, however for now your suggestion is sufficient.
