### ISSUE TITLE
Managers cannot view self-reviews

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2657]
Managers or other reviewers should be able to access the self-review of the person they are reviewing. Currently, those are not accessible.

https://github.com/user-attachments/assets/da0f077b-4c07-4ad7-b82e-b8ac8833ca83

Ideally this would work similarly to the current production functionality:

https://github.com/user-attachments/assets/d6aa6356-5d43-4296-a10a-b513b599a5fb

**Comment by ocielliottc** [comment]
@mkimberlin The self review of the reviewee, if submitted, is actually viewable via the link of the reviewer.  There will be two tabs in the resulting page, the first is the self-review and the second would be for reviewing the reviewee.  The self-review chip never has a link.

**Comment by mkimberlin** [comment]
@ocielliottc I don't think I saw that behavior. Could you verify that in Dev just to be sure? I'm on a plane. 🤣
