### ISSUE TITLE
Creating a new organization allows empty website

### ISSUE THREAD

**Issue by ocielliottc** [objectcomputing/check-ins#2664]
**Describe the bug**
The `volunteering_organization` table says that the website should not be null.  The `VolunteeringOrganization` java class says that it should not be blank.  The UI has the website portion as optional.

**To Reproduce**
1. Go to Volunteering under reports.
2. Click on the + circle.
3. Click on Organization.
4. Click on Create a New Organization.
5. Fill in everything but the website.
6. Click Save.
7. Get "Bad Request" error.

**Expected behavior**
I'm not sure if the UI or the DB needs to change.

**Comment by mkimberlin** [comment]
I would adjust the DB, I think. I'm sure some organizations don't have websites.

**Comment by ocielliottc** [comment]
> I would adjust the DB, I think. I'm sure some organizations don't have websites.

Excellent!  That was my guess.
