### ISSUE TITLE
Role added to member does not receive permissions related to that role until after server restart

### ISSUE THREAD

**Issue by ocielliottc** [objectcomputing/check-ins#2686]
**Describe the bug**
If you add a role to a member, the member receives the role but when the member profile is pulled from the server, it does not contain the permissions for the newly added role.

**To Reproduce**
1. Start with a fresh database in dev.
2. Add the PDL role to the Kazuhira Miller member.
3. Log in as Kazuhira Miller, view the permissions from the "current" network call (i.e., http://localhost:8080/services/member-profiles/current)
4. The permissions listed will be only the MEMBER permissions.

**Expected behavior**
The PDL permissions should be part of the member profile "permissions" array.

The attached faux_freddy.json shows both the MEMBER and PDL permissions because he was already a PDL when the instance started up.  The attached kaz_miller.json has both the MEMBER and PDL roles.  But, only shows the MEMBER permissions.
[faux_freddy.json](https://github.com/user-attachments/files/17577251/faux_freddy.json)
[kaz_miller.json](https://github.com/user-attachments/files/17577254/kaz_miller.json)

**Comment by ocielliottc** [comment]
I am guessing there is caching going on at the micronaut level, maybe?

**Comment by mkimberlin** [comment]
💯 - Caching
[Cache Applied](https://github.com/objectcomputing/check-ins/blob/2d56520c0588c7a68391c3520f5105d5a8813d34/server/src/main/java/com/objectcomputing/checkins/services/role/role_permissions/RolePermissionServicesImpl.java#L21)
[Cache Config](https://github.com/objectcomputing/check-ins/blob/2d56520c0588c7a68391c3520f5105d5a8813d34/server/src/main/resources/application.yml#L17)
