### ISSUE TITLE
Server-side markdown generation - merit report

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2759]
Refactor the generation of the Markdown and the storage of the files on Google Drive so that the data is never transmitted to the frontend (generate the markdown on the server and make the file storage calls from there).

## Bonus points
 - [x] Storing each report before continuing on to gathering data for the next one
 - [x] Move the selected report IDs from query parameters to the body of the request

**Comment by ocielliottc** [comment]
I have the server side generation coded.  However, it has not been fully tested.

https://github.com/objectcomputing/check-ins/tree/feature-2759/server-side-markdown-generation
