### ISSUE TITLE
New Team Member Error

### ISSUE THREAD

**Issue by AndrewBarbaglia** [objectcomputing/check-ins#2785]
**Describe the bug**
After I create and save a new team member, when I click "Add Member" again to add another it autofills with the team member I just created.

**To Reproduce**
1. Go to Check-ins
2. Click on Add Member
3. Fill in information and save
4. Click Add Member again and see previously entered information

**Expected behavior**
Blank form when entering a new team member.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacBook Pro]
 - Browser [Chrome]

**Additional context**

**Comment by ocielliottc** [comment]
@AndrewBarbaglia Under expected behavior, you put the behavior that is currently exhibited.  I am assuming that this is the behavior that we do **not** want.
@mkimberlin What should we do in this situation?  Auto-fill nothing?

**Comment by AndrewBarbaglia** [comment]
Sorry, you are correct that should not be expected.
