### ISSUE TITLE
Include the number of responses in the pulse survey report chart

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2790]
**Is your feature request related to a problem? Please describe.**
When looking at the chart at the top of the Pulse Report (Menu: REPORTS -> Pulses) the scores for a given day are available, but there is no indication of how many responses there were that day. This makes it hard to weigh the value of a given data point on the chart.

**Describe the solution you'd like**
Include a combined bar chart showing the number of responses.

**Describe alternatives you've considered**
Adding the number of responses to the hover over or completely changing the chart type.

**Additional context**
Something similar to this would be great: https://codesandbox.io/p/sandbox/recharts-linebar-chart-ribni/

**Comment by ocielliottc** [comment]
![chart](https://github.com/user-attachments/assets/b7002827-2bad-4cb0-9483-db30ad3d6082)
@mkimberlin Was this what you were looking for?  Or did you want an actual bar chart?

**Comment by mkimberlin** [comment]
> ![chart](https://github.com/user-attachments/assets/b7002827-2bad-4cb0-9483-db30ad3d6082)
> @mkimberlin Was this what you were looking for?  Or did you want an actual bar chart?

@ocielliottc bar chart combo. See the link under additional context in the description

**Comment by ocielliottc** [comment]
@mkimberlin I did prior to starting on this.  All I initially saw was a line chart.  I just now saw that there is an extremely light colored bar chart!

**Comment by mkimberlin** [comment]
@ocielliottc lol. That is a bit light.   ...and I just spent more time than I care to admit trying to figure out who I could jokingly blame for it, but I didn't see an authorship indicator anywhere 🤷 😶

**Comment by ocielliottc** [comment]
I think my old eyes just couldn't see it!

![barchart](https://github.com/user-attachments/assets/82c30d35-cabe-4de8-b55d-353075f9f901)
Here we go!
