### ISSUE TITLE
FE > Implementing feature test

### ISSUE THREAD

**Issue by sharmag04** [objectcomputing/check-ins#36]
This story is to leverage the front-end, end-to-end scriptable solution with a chrome web driver tool like selenium.

Definition of Done

- [ ] have working feature test
- [ ] integration into the build
- [ ] publish results

**Comment by mkimberlin** [comment]
What will be using? Selenium? Geb? Nightmare.js?

**Comment by jorwalk** [comment]
If my understanding is correct we are looking to be able to script the interaction of the front end through an automation type framework you mentioned... I would to with Selenium as that is what our QA testing team has been rallying behind. There is some opportunity to overlap skill sets.
